scrape_configs:
  - job_name: 'yarkozloff_metrics'
    static_configs:
      - targets: ['node-exporter:9100']
  
  - job_name: 'postgres_metrics'
    static_configs:
      - targets: ['pg-exporter:9187']
